---
name: test
---

## Publications

[***Wage Differences Matter: An Experiment of Social Comparison and Effort Provision when Wages Increase or Decrease***](Wage-Differences-Matter-An-Experiment-of-Social-Comparison-and-Effort-Provision.pdf) with [J. Forrest Williams](https://www.pdx.edu/economics/j-forrest-williams), *Games (2020)*

## Working Papers

***Does the Global South Import Ideology Shifts? Evidence from Costa Rica and CAFTA-DR*** [[PDF]](Field-Paper-CAFTA-and-Political-Lean-in-CRC.pdf)

Has increased access to international markets contributed to political ideology shifts in developing economies?
Does ones ex-ante opinion on international trade impact their political leaning after international market access has begun?
Previous research has shown that regions impacted negatively by trade have shifted toward political extremes but due to nonexistent regional level information on support for trade, there has been little said about how people's perception of trade may impact outcomes. 
Using the unique circumstance of Costa Rica, which placed their decision to join the Free Trade Agreement CAFTA-DR on their populace via a democratic referendum in 2007.
I use county-level vote share of support for CAFTA-DR as a proxy of direct opinion on trade. 
I use political party election manifesto data to rank political leans left-to-right interacted with their received vote share at the county-level to create a county-political-lean index.
Assuming that an individuals' political decision is impacted by the most recent comparative difference, I measure a counties exposure to imports for each election cycle. 
Results align with previous research and show that increased import competition shifts political support toward right-leaning ideologies.
Interestingly, this effect diminishes as support for trade increases. 
This finding gives further evidence of links between adverse economic shocks to ideological shifts while adding the role of economic agent perception of trade and their interpretation of outcomes from it.

## Works in Progress

***eDACAtion: Are Higher Education Attainment Benefits Equally Distributed?***


