project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Jose Alberto Rojas Fallas"
  favicon: UO-icon.png

  page-footer:
    left: "&copy; Copyright 2024, Jose A. Rojas Fallas"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    right:
      - href: main-page.qmd
        text: Home

      - href: projects/research-agenda.qmd
        text: Research
        
      - href: teaching/courses.qmd
        text: Teaching

format:
  html:
    theme:
      - styles.scss
    mainfont: Tauri
    toc: true
    page-layout: full 
    



