project:
  type: website
  output-dir: docs
  resources:
    - files/images/UO-icon.png   

website:
  page-navigation: true
  title: "Jose Alberto Rojas Fallas"
  favicon: files/images/UO-icon.png

  page-footer:
    left: "&copy; Copyright 2025, Jose A. Rojas Fallas"
    right: "2025-2026 Job Market Candidate"

  navbar:
    pinned: true
    right:      
      - text: Research
        href: research-agenda.qmd

      - href: teaching-experience.qmd
        text: Teaching

      - href: bio.qmd
        text: Bio

      - href: files/documents/rojas-cv.pdf
        text: CV
        target: _blank

format:
  html:
    theme:
      light: styles.scss
      dark: darkly
    mainfont: Tauri
    toc: true
    page-layout: full 
    toggle: true