---
name: contribution
---

## Preview of Results 

::: {.small}
- A shift from low to high exposure to [Manufacturing MNCs]{.hp} increases the probability of choosing a major within [Stem and Applied Sciences by 52.9 p.p.]{.hp} 
    - [Decreases probability of choosing Arts by 25 p.p. and Social Sciences by 27.9 p.p.]{.h}
- A shift from low to high exposure to [Administrative Service MNCs]{.hp} increases the probability of choosing a major within [Social Sciences and Professional Studies by 39.81 p.p.]{.hp}
    - [Decreases the probability of choosing Arts by 30.58 p.p. and STEM and Applied Sciences by 8.96 p.p.]{.h}

- Directional effects are robust to removing the industry-field mapping
- Multinational Firm effects are extremely local
- Heterogeneity tests show no difference between men and women
:::

::: {.notes}
distance decay: Strong within 5km but decays rapidly. Students respond to hyper-local labor-market signals.
:::

---

## Contributions

[Mechanism of fdi shifting human capital specialization decisions]{.hi-green .align-center}

[Determinants of College Major Choice]{.hp}

- [Information availability]{.hi .small}
    - [@jensen_perceived_2010, @kaufmann_understanding_2014]{.tiny}
- [Wages]{.hi .small}
    - [@carneiro_estimating_2011, @arcidiacono_modeling_2012, @arcidiacono_ex_2020, @beffy_choosing_2012, @carroll_why_2014, @kirkeboen_field_2016, @bleemer_will_2022]{.tiny}
- [Non-pecuniary returns]{.hi .small}
    - [@altonji_demand_1993]{.tiny}
- [Ability and preference sorting]{.hi .small}
    - [@arcidiacono_ability_2004, @kinsler_specificity_2015]{.tiny}

---

## Contributions

[Mechanism of fdi shifting human capital specialization decisions]{.hi-green .align-center}

::: {.faded}
[Determinants of College Major Choice]{.hp .small}

- [Wages]{.hi .small} | [Non-pecuniary returns]{.hi .small} | [Ability and preference sorting]{.hi .small} | [Information availability]{.hi .small}
:::

[Effects of increased trade/fdi inflow on local labor markets]{.hp}

- [Increase in skilled labor demand]{.hi .small}
    - [@feenstra_foreign_1997, @JavorcikBeataS.2015DFBG, @alfaro-urena_effects_2021, @setzler_effects_2021]{.tiny}
- [Skill acquisition decisions]{.hi .small}
    - [@blanchard_trade_2016]{.tiny}
